name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'welcome! if you're new here is what you need to know.'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'
